jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3.5.3
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v3.11.0
      with:
        cache: maven
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Build
      run: mvn -B -ntp verify
name: CI Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
